// Sample word database - can be easily extended
export const WORD_DATABASE = [
  // Animals - Easy
  {
    word: "猫",
    furigana: "ねこ",
    ngWords: ["animal", "meow", "pet", "feline"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "犬",
    furigana: "いぬ",
    ngWords: ["animal", "bark", "pet", "puppy"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "鳥",
    furigana: "とり",
    ngWords: ["animal", "fly", "wing", "sky"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "魚",
    furigana: "さかな",
    ngWords: ["animal", "water", "swim", "ocean"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "馬",
    furigana: "うま",
    ngWords: ["animal", "ride", "brown", "farm"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "牛",
    furigana: "うし",
    ngWords: ["animal", "milk", "farm", "meat"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "象",
    furigana: "ぞう",
    ngWords: ["animal", "trunk", "large", "africa"],
    category: "animals",
    difficulty: "medium",
  },
  {
    word: "熊",
    furigana: "くま",
    ngWords: ["animal", "bear", "wild", "forest"],
    category: "animals",
    difficulty: "easy",
  },
  {
    word: "ライオン",
    furigana: "ライオン",
    ngWords: ["animal", "lion", "roar", "africa"],
    category: "animals",
    difficulty: "medium",
  },
  {
    word: "蛇",
    furigana: "へび",
    ngWords: ["animal", "dangerous", "reptile", "scales"],
    category: "animals",
    difficulty: "medium",
  },

  // Nature - Easy
  {
    word: "木",
    furigana: "き",
    ngWords: ["plant", "nature", "wood", "green"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "水",
    furigana: "みず",
    ngWords: ["liquid", "drink", "river", "wet"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "火",
    furigana: "ひ",
    ngWords: ["heat", "burn", "hot", "flame"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "雲",
    furigana: "くも",
    ngWords: ["sky", "weather", "white", "rain"],
    category: "nature",
    difficulty: "medium",
  },
  {
    word: "花",
    furigana: "はな",
    ngWords: ["plant", "pretty", "nature", "color"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "山",
    furigana: "やま",
    ngWords: ["nature", "high", "terrain", "climb"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "海",
    furigana: "うみ",
    ngWords: ["water", "nature", "salt", "beach"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "川",
    furigana: "かわ",
    ngWords: ["water", "nature", "flow", "bridge"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "草",
    furigana: "くさ",
    ngWords: ["plant", "green", "nature", "ground"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "石",
    furigana: "いし",
    ngWords: ["hard", "nature", "rock", "ground"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "太陽",
    furigana: "たいよう",
    ngWords: ["sky", "hot", "bright", "energy"],
    category: "nature",
    difficulty: "medium",
  },
  {
    word: "月",
    furigana: "つき",
    ngWords: ["night", "sky", "round", "bright"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "星",
    furigana: "ほし",
    ngWords: ["night", "sky", "twinkle", "space"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "風",
    furigana: "かぜ",
    ngWords: ["air", "nature", "move", "invisible"],
    category: "nature",
    difficulty: "easy",
  },
  {
    word: "雨",
    furigana: "あめ",
    ngWords: ["water", "sky", "weather", "wet"],
    category: "nature",
    difficulty: "easy",
  },

  // Objects - Easy
  {
    word: "机",
    furigana: "つくえ",
    ngWords: ["furniture", "desk", "work", "wood"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "椅子",
    furigana: "いす",
    ngWords: ["furniture", "sit", "object"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "本",
    furigana: "ほん",
    ngWords: ["read", "paper", "story", "pages"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "ペン",
    furigana: "ペン",
    ngWords: ["write", "object", "ink", "tool"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "キー",
    furigana: "キー",
    ngWords: ["open", "metal", "door", "lock"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "ドア",
    furigana: "ドア",
    ngWords: ["enter", "open", "room", "object"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "窓",
    furigana: "まど",
    ngWords: ["room", "glass", "light", "outside"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "テーブル",
    furigana: "テーブル",
    ngWords: ["furniture", "eat", "surface"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "ベッド",
    furigana: "ベッド",
    ngWords: ["sleep", "furniture", "rest"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "シャツ",
    furigana: "シャツ",
    ngWords: ["clothing", "wear", "cloth"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "ズボン",
    furigana: "ズボン",
    ngWords: ["clothing", "wear", "legs"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "靴",
    furigana: "くつ",
    ngWords: ["clothing", "feet", "wear", "walk"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "カップ",
    furigana: "カップ",
    ngWords: ["drink", "container", "object"],
    category: "objects",
    difficulty: "easy",
  },
  {
    word: "スプーン",
    furigana: "スプーン",
    ngWords: ["eat", "utensil", "object"],
    category: "objects",
    difficulty: "medium",
  },
  {
    word: "フォーク",
    furigana: "フォーク",
    ngWords: ["eat", "utensil", "object"],
    category: "objects",
    difficulty: "medium",
  },

  // Time - Medium
  {
    word: "時間",
    furigana: "じかん",
    ngWords: ["clock", "watch", "minute", "second"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "昨日",
    furigana: "きのう",
    ngWords: ["day", "past", "24 hours", "before today"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "明日",
    furigana: "あした",
    ngWords: ["day", "future", "24 hours", "after today"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "今日",
    furigana: "きょう",
    ngWords: ["day", "present", "24 hours", "now"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "朝",
    furigana: "あさ",
    ngWords: ["time", "morning", "sunrise", "early"],
    category: "time",
    difficulty: "easy",
  },
  {
    word: "昼",
    furigana: "ひる",
    ngWords: ["time", "noon", "day", "bright"],
    category: "time",
    difficulty: "easy",
  },
  {
    word: "夜",
    furigana: "よる",
    ngWords: ["time", "night", "dark", "sleep"],
    category: "time",
    difficulty: "easy",
  },
  {
    word: "週",
    furigana: "しゅう",
    ngWords: ["time", "seven days", "period"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "月",
    furigana: "つき",
    ngWords: ["time", "twelve times", "period"],
    category: "time",
    difficulty: "medium",
  },
  {
    word: "年",
    furigana: "ねん",
    ngWords: ["time", "twelve months", "period"],
    category: "time",
    difficulty: "easy",
  },

  // Places - Medium
  {
    word: "学校",
    furigana: "がっこう",
    ngWords: ["education", "student", "teacher", "study"],
    category: "places",
    difficulty: "easy",
  },
  {
    word: "病院",
    furigana: "びょういん",
    ngWords: ["sick", "doctor", "medicine", "health"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "駅",
    furigana: "えき",
    ngWords: ["train", "transport", "travel", "platform"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "店",
    furigana: "みせ",
    ngWords: ["buy", "sell", "shopping", "money"],
    category: "places",
    difficulty: "easy",
  },
  {
    word: "家",
    furigana: "いえ",
    ngWords: ["live", "building", "shelter", "family"],
    category: "places",
    difficulty: "easy",
  },
  {
    word: "オフィス",
    furigana: "オフィス",
    ngWords: ["work", "building", "desk"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "レストラン",
    furigana: "レストラン",
    ngWords: ["eat", "food", "place"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "図書館",
    furigana: "としょかん",
    ngWords: ["books", "read", "quiet", "study"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "公園",
    furigana: "こうえん",
    ngWords: ["outside", "nature", "play", "green"],
    category: "places",
    difficulty: "medium",
  },
  {
    word: "市場",
    furigana: "いちば",
    ngWords: ["buy", "sell", "food", "market"],
    category: "places",
    difficulty: "hard",
  },

  // Emotions - Medium
  {
    word: "楽しい",
    furigana: "たのしい",
    ngWords: ["happy", "fun", "enjoy", "smile"],
    category: "emotions",
    difficulty: "medium",
  },
  {
    word: "悲しい",
    furigana: "かなしい",
    ngWords: ["sad", "cry", "unhappy", "emotion"],
    category: "emotions",
    difficulty: "medium",
  },
  {
    word: "怖い",
    furigana: "こわい",
    ngWords: ["afraid", "scary", "fear", "emotion"],
    category: "emotions",
    difficulty: "medium",
  },
  {
    word: "嬉しい",
    furigana: "うれしい",
    ngWords: ["happy", "glad", "pleased", "smile"],
    category: "emotions",
    difficulty: "medium",
  },
  {
    word: "怒っている",
    furigana: "おこっている",
    ngWords: ["angry", "mad", "upset", "emotion"],
    category: "emotions",
    difficulty: "hard",
  },
  {
    word: "驚いた",
    furigana: "おどろいた",
    ngWords: ["surprised", "shock", "unexpected"],
    category: "emotions",
    difficulty: "hard",
  },
  {
    word: "退屈",
    furigana: "たいくつ",
    ngWords: ["bored", "dull", "uninterested"],
    category: "emotions",
    difficulty: "hard",
  },
  {
    word: "緊張",
    furigana: "きんちょう",
    ngWords: ["nervous", "tense", "anxious", "stress"],
    category: "emotions",
    difficulty: "hard",
  },

  // Adjectives - Easy/Medium
  {
    word: "速い",
    furigana: "はやい",
    ngWords: ["quick", "fast", "time", "race"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "遅い",
    furigana: "おそい",
    ngWords: ["slow", "late", "time", "behind"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "大きい",
    furigana: "おおきい",
    ngWords: ["size", "big", "large", "huge"],
    category: "adjectives",
    difficulty: "easy",
  },
  {
    word: "小さい",
    furigana: "ちいさい",
    ngWords: ["size", "little", "tiny", "small"],
    category: "adjectives",
    difficulty: "easy",
  },
  {
    word: "長い",
    furigana: "ながい",
    ngWords: ["length", "extend", "distance", "not short"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "短い",
    furigana: "みじかい",
    ngWords: ["length", "brief", "not long", "distance"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "高い",
    furigana: "たかい",
    ngWords: ["height", "tall", "expensive", "up"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "低い",
    furigana: "ひくい",
    ngWords: ["height", "short", "down", "beneath"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "熱い",
    furigana: "あつい",
    ngWords: ["temperature", "hot", "heat", "fire"],
    category: "adjectives",
    difficulty: "easy",
  },
  {
    word: "冷たい",
    furigana: "つめたい",
    ngWords: ["temperature", "cold", "cool", "ice"],
    category: "adjectives",
    difficulty: "medium",
  },
  {
    word: "美しい",
    furigana: "うつくしい",
    ngWords: ["appearance", "pretty", "beautiful", "lovely"],
    category: "adjectives",
    difficulty: "hard",
  },
  {
    word: "汚い",
    furigana: "きたない",
    ngWords: ["clean", "dirty", "messy", "appearance"],
    category: "adjectives",
    difficulty: "medium",
  },

  // Food - Easy/Medium
  {
    word: "ご飯",
    furigana: "ごはん",
    ngWords: ["eat", "rice", "food"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "パン",
    furigana: "パン",
    ngWords: ["eat", "bread", "food"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "リンゴ",
    furigana: "りんご",
    ngWords: ["fruit", "red", "eat", "food"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "みかん",
    furigana: "みかん",
    ngWords: ["fruit", "orange", "citrus", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "バナナ",
    furigana: "バナナ",
    ngWords: ["fruit", "yellow", "peel", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "トマト",
    furigana: "トマト",
    ngWords: ["vegetable", "red", "round", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "ニンジン",
    furigana: "ニンジン",
    ngWords: ["vegetable", "orange", "root", "eat"],
    category: "food",
    difficulty: "medium",
  },
  {
    word: "タマネギ",
    furigana: "たまねぎ",
    ngWords: ["vegetable", "layer", "cry", "eat"],
    category: "food",
    difficulty: "hard",
  },
  {
    word: "牛乳",
    furigana: "ぎゅうにゅう",
    ngWords: ["drink", "cow", "white", "dairy"],
    category: "food",
    difficulty: "medium",
  },
  {
    word: "チーズ",
    furigana: "チーズ",
    ngWords: ["dairy", "yellow", "food", "milk"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "バター",
    furigana: "バター",
    ngWords: ["dairy", "yellow", "soft", "spread"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "肉",
    furigana: "にく",
    ngWords: ["food", "animal", "protein", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "魚",
    furigana: "さかな",
    ngWords: ["food", "ocean", "protein", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "卵",
    furigana: "たまご",
    ngWords: ["chicken", "round", "breakfast", "eat"],
    category: "food",
    difficulty: "easy",
  },
  {
    word: "スープ",
    furigana: "スープ",
    ngWords: ["hot", "liquid", "eat", "food"],
    category: "food",
    difficulty: "medium",
  },
  {
    word: "スイーツ",
    furigana: "スイーツ",
    ngWords: ["sweet", "dessert", "sugar", "eat"],
    category: "food",
    difficulty: "hard",
  },

  // Actions/Verbs - Medium
  {
    word: "食べる",
    furigana: "たべる",
    ngWords: ["consume", "mouth", "food", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "飲む",
    furigana: "のむ",
    ngWords: ["liquid", "mouth", "swallow", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "書く",
    furigana: "かく",
    ngWords: ["pen", "paper", "mark", "action"],
    category: "actions",
    difficulty: "easy",
  },
  {
    word: "読む",
    furigana: "よむ",
    ngWords: ["book", "text", "eye", "action"],
    category: "actions",
    difficulty: "easy",
  },
  {
    word: "走る",
    furigana: "はしる",
    ngWords: ["move", "fast", "legs", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "歩く",
    furigana: "あるく",
    ngWords: ["move", "legs", "slow", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "寝る",
    furigana: "ねる",
    ngWords: ["sleep", "night", "rest", "action"],
    category: "actions",
    difficulty: "easy",
  },
  {
    word: "起きる",
    furigana: "おきる",
    ngWords: ["wake", "morning", "rise", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "座る",
    furigana: "すわる",
    ngWords: ["chair", "rest", "down", "action"],
    category: "actions",
    difficulty: "medium",
  },
  {
    word: "立つ",
    furigana: "たつ",
    ngWords: ["stand", "up", "legs", "action"],
    category: "actions",
    difficulty: "easy",
  },
  {
    word: "見る",
    furigana: "みる",
    ngWords: ["eyes", "watch", "observe", "action"],
    category: "actions",
    difficulty: "easy",
  },
  {
    word: "聞く",
    furigana: "きく",
    ngWords: ["ears", "sound", "listen", "action"],
    category: "actions",
    difficulty: "easy",
  },

  // Colors - Easy
  {
    word: "赤",
    furigana: "あか",
    ngWords: ["color", "tomato", "fire", "blood"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "青",
    furigana: "あお",
    ngWords: ["color", "sky", "ocean", "sad"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "黄色",
    furigana: "きいろ",
    ngWords: ["color", "sun", "banana", "bright"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "緑",
    furigana: "みどり",
    ngWords: ["color", "plant", "tree", "grass"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "白",
    furigana: "しろ",
    ngWords: ["color", "snow", "milk", "pure"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "黒",
    furigana: "くろ",
    ngWords: ["color", "night", "dark", "coal"],
    category: "colors",
    difficulty: "easy",
  },
  {
    word: "オレンジ",
    furigana: "オレンジ",
    ngWords: ["color", "fruit", "warm"],
    category: "colors",
    difficulty: "medium",
  },
  {
    word: "紫",
    furigana: "むらさき",
    ngWords: ["color", "grape", "royal"],
    category: "colors",
    difficulty: "hard",
  },

  // Family - Medium
  {
    word: "父",
    furigana: "ちち",
    ngWords: ["family", "man", "parent", "male"],
    category: "family",
    difficulty: "medium",
  },
  {
    word: "母",
    furigana: "はは",
    ngWords: ["family", "woman", "parent", "female"],
    category: "family",
    difficulty: "medium",
  },
  {
    word: "兄",
    furigana: "あに",
    ngWords: ["family", "boy", "older", "male"],
    category: "family",
    difficulty: "hard",
  },
  {
    word: "姉",
    furigana: "あね",
    ngWords: ["family", "girl", "older", "female"],
    category: "family",
    difficulty: "hard",
  },
  {
    word: "弟",
    furigana: "おとうと",
    ngWords: ["family", "boy", "younger", "male"],
    category: "family",
    difficulty: "hard",
  },
  {
    word: "妹",
    furigana: "いもうと",
    ngWords: ["family", "girl", "younger", "female"],
    category: "family",
    difficulty: "hard",
  },
  {
    word: "祖母",
    furigana: "そぼ",
    ngWords: ["family", "old", "woman", "grandparent"],
    category: "family",
    difficulty: "hard",
  },
  {
    word: "祖父",
    furigana: "そふ",
    ngWords: ["family", "old", "man", "grandparent"],
    category: "family",
    difficulty: "hard",
  },

  // Numbers - Easy
  {
    word: "一",
    furigana: "いち",
    ngWords: ["number", "count", "one"],
    category: "numbers",
    difficulty: "easy",
  },
  {
    word: "二",
    furigana: "に",
    ngWords: ["number", "count", "two"],
    category: "numbers",
    difficulty: "easy",
  },
  {
    word: "三",
    furigana: "さん",
    ngWords: ["number", "count", "three"],
    category: "numbers",
    difficulty: "easy",
  },
  {
    word: "十",
    furigana: "じゅう",
    ngWords: ["number", "count", "ten"],
    category: "numbers",
    difficulty: "easy",
  },
  {
    word: "百",
    furigana: "ひゃく",
    ngWords: ["number", "count", "hundred"],
    category: "numbers",
    difficulty: "medium",
  },
  {
    word: "千",
    furigana: "せん",
    ngWords: ["number", "count", "thousand"],
    category: "numbers",
    difficulty: "medium",
  },

  // School - Medium
  {
    word: "先生",
    furigana: "せんせい",
    ngWords: ["education", "teach", "adult", "school"],
    category: "school",
    difficulty: "medium",
  },
  {
    word: "生徒",
    furigana: "せいと",
    ngWords: ["education", "learn", "young", "school"],
    category: "school",
    difficulty: "hard",
  },
  {
    word: "テスト",
    furigana: "テスト",
    ngWords: ["education", "exam", "score", "check"],
    category: "school",
    difficulty: "medium",
  },
  {
    word: "宿題",
    furigana: "しゅくだい",
    ngWords: ["education", "home", "study", "work"],
    category: "school",
    difficulty: "hard",
  },

  // Body - Medium
  {
    word: "頭",
    furigana: "あたま",
    ngWords: ["body", "brain", "hair", "top"],
    category: "body",
    difficulty: "medium",
  },
  {
    word: "目",
    furigana: "め",
    ngWords: ["body", "see", "face", "pair"],
    category: "body",
    difficulty: "easy",
  },
  {
    word: "耳",
    furigana: "みみ",
    ngWords: ["body", "hear", "sound", "pair"],
    category: "body",
    difficulty: "medium",
  },
  {
    word: "鼻",
    furigana: "はな",
    ngWords: ["body", "smell", "face", "breathe"],
    category: "body",
    difficulty: "medium",
  },
  {
    word: "口",
    furigana: "くち",
    ngWords: ["body", "eat", "speak", "face"],
    category: "body",
    difficulty: "easy",
  },
  {
    word: "手",
    furigana: "て",
    ngWords: ["body", "hold", "arm", "fingers"],
    category: "body",
    difficulty: "easy",
  },
  {
    word: "足",
    furigana: "あし",
    ngWords: ["body", "walk", "run", "leg"],
    category: "body",
    difficulty: "easy",
  },
  {
    word: "心臓",
    furigana: "しんぞう",
    ngWords: ["body", "beat", "organ", "life"],
    category: "body",
    difficulty: "hard",
  },
];
